#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

MIRROR_DIR=/etc/pacman.d/
MIRROR_LIST=$MIRROR_DIR/mirrorlist
ALL_MIRRORS=$MIRROR_DIR/mirrorlist_all
OLD_MIRRORS=$MIRROR_DIR/mirrorlist_old
cp $MIRROR_LIST $OLD_MIRRORS
printf 'Downloading mirror list...\n'
curl https://www.archlinux.org/mirrorlist/all/https/ | sed 's/^#Server/Server/g; /^## .*$/d; /^$/d; s/^Server/# ~~~\nServer/' > $ALL_MIRRORS
printf 'Sorting mirror list...\n'
rankmirrors -n 6 $ALL_MIRRORS | tee $MIRROR_LIST | grep --line-buffered '~~~' | pv --size $(grep '~~~' $ALL_MIRRORS | wc -c) > /dev/null
#cp $ALL_MIRRORS $MIRROR_LIST
sed -i '/^# ~~~$/d; s/# Server list/# Generated by wmww hacky script\n# Server list/g' $MIRROR_LIST
printf 'updating pacman...\n'
if pacman -Syy ; then
    printf 'ranked mirrors:\n'
    cat $MIRROR_LIST
else
    printf 'something is wrong, restoring old mirror list\n'
    cp $OLD_MIRRORS $MIRROR_LIST
fi
printf 'done\n'
